- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

  # Gazebo -> ROS (LaserScan)
- ros_topic_name: "scan"
  gz_topic_name: "scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

  # Gazebo -> ROS (IMU)
- ros_topic_name: "imu"
  gz_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  
# Gazebo -> ROS (Imagen de Profundidad)
- ros_topic_name: "camera/depth_image"
  gz_topic_name: "world/empty_world/model/diffbot/link/base_link/sensor/camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

  # Gazebo -> ROS (Nube de Puntos)
- ros_topic_name: "camera/points"
  gz_topic_name: "world/empty_world/model/diffbot/link/base_link/sensor/camera/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

  # Gazebo -> ROS (Camera Info)
- ros_topic_name: "camera/camera_info"
  gz_topic_name: "world/empty_world/model/diffbot/link/base_link/sensor/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

